# Generated by Django 5.0 on 2026-01-06 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Unique permission code (e.g., 'courses.enroll')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what this permission allows')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this permission is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique role name (e.g., 'Student', 'Instructor')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this role and its purpose')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this role is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted by this role', related_name='roles', to='authz.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.BooleanField(default=True, help_text='True = explicitly allow, False = explicitly deny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this permission override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(help_text='Permission being granted or denied', on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='authz.permission')),
                ('user', models.ForeignKey(help_text='User to whom this permission override applies', on_delete=django.db.models.deletion.CASCADE, related_name='authz_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'permission'], name='authz_userp_user_id_a0e1eb_idx'), models.Index(fields=['user', 'allow'], name='authz_userp_user_id_27b41c_idx')],
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='authz.role')),
                ('user', models.ForeignKey(help_text='User to whom this role is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'role'], name='authz_userr_user_id_707d2c_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
